name: aws-org-required-tags
description: Detects all supported resources that can require tags, and sets required tags
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
